#!/usr/bin/env bash
# Print a complete Teleport join token for one cluster's issuer bot, with the
# cluster's ServiceAccount signing keys already filled in.
#
#   scripts/make-token.sh k8s-prod | tctl create -f -
#   tctl bots add k8s-prod --roles=workload-identity-issuer --token=k8s-prod-issuer
#
# Reads the keys from the CURRENT kubectl context (kubectl get --raw
# /openid/v1/jwks), so run it while pointed at the cluster the issuer will run
# in. The bot name should be the cluster's name: it becomes the SVID hint and
# the JWT's kube.cluster claim.
#
# join_method: kubernetes with static_jwks — the Auth Service verifies each
# DaemonSet pod's projected ServiceAccount token against these keys, so it
# works when the Auth Service cannot reach the cluster (Teleport Cloud). If the
# cluster's keys rotate or the cluster is rebuilt, run this again and recreate
# the token (scripts/jwks.sh --check <token> tells you when).
set -euo pipefail

bot="${1:?usage: make-token.sh <bot-name>   (use the name of the Kubernetes cluster)}"
jwks=$(kubectl get --raw /openid/v1/jwks | tr -d '\n')
[ -n "$jwks" ] || { echo "make-token.sh: could not read /openid/v1/jwks from the current context" >&2; exit 1; }
ctx=$(kubectl config current-context 2>/dev/null || echo unknown)

cat <<EOF
# Join token for the Workload Identity issuer on Kubernetes cluster "${bot}".
# Generated by scripts/make-token.sh from kubectl context "${ctx}".
kind: token
version: v2
metadata:
  name: ${bot}-issuer
spec:
  roles: [Bot]
  bot_name: ${bot}
  join_method: kubernetes
  kubernetes:
    type: static_jwks
    static_jwks:
      jwks: |
        ${jwks}
    allow:
      - service_account: "teleport-wi:tbot"
EOF
